### ISSUE TITLE
eTIMS API

### ISSUE THREAD

**Issue by edumachah** [Nicholas-Kipkoech/icon-x-KRA#1]
Hi Nicholas,

Do you have access to the official eTIMS API documentation from KRA?

Thanks

**Comment by Nicholas-Kipkoech** [comment]
Yes i have it, whats your email i can share

**Comment by edumachah** [comment]
`bunifuanalytica@gmail.com`

Thanks in advance.

**Comment by kevinwaxi** [comment]
kevinwakhisi70@gmail.com

**Comment by Nicholas-Kipkoech** [comment]
@kevinwaxi sharing ASAP

**Comment by kevinwaxi** [comment]
> @kevinwaxi sharing ASAP

Did you share any documents with my email?

**Comment by Nicholas-Kipkoech** [comment]
@kevinwaxi  Yes I shared in Jan 19
